## Algebra liniowa - biblioteki numeryczne 
W środowisku języka Python dostępne są dwie biblioteki numeryczne numpy i scipy. Dokumentacja: https://numpy.org/doc/, https://docs.scipy.org/doc/. Znajdź informacje wyjaśniające różnice między tymi bibliotekami. 

### Zadanie 1
Napisz krótki program, który wyświetli informację o wersji biblioteki oraz jej konfiguracji. Zwróć uwagę z jakich bibliotek numerycznych korzystają biblioteki Python'a

In [18]:
import numpy as np
print("Wersja numpy:", np.__version__, '\n')
print("Konfiguracja numpy:")
np.__config__.show()

Wersja numpy: 1.14.3 

Konfiguracja numpy:
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
blas_opt_info:
    extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_clapack_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_opt_info:
    extra_compile_args = ['-msse3']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]


In [9]:
import scipy as scp
print("Wersja scipy:", scp.__version__, '\n')
print("Weersja numpy w scipy:", scp.__numpy_version__, '\n')
print("Konfiguracja scipy:")
scp.__config__.show()

Wersja scipy: 1.1.0 

Weersja numpy w scipy: 1.14.3 

Konfiguracja scipy:
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_clapack_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_opt_info:
    extra_compile_args = ['-msse3']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
blas_opt_info:
    extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]


### Zadanie 2 
Napisz program, który wyświetla wbudowaną pomoc dla funkcji: dodawanie wektorów, 

In [2]:
import numpy as np

print("Help for function adding vectors:\n")
np.info(np.add)


Help for function adding vectors:

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
----

### Zadanie 3
Napisz programy, które testują wektory danych pod kątem obecności elementów zerowych lub nieskończonych (sprawdź różne warianty takich funkcji). 
Napisz program porównujące wektory i macierze (według wartości elementów).

In [7]:
import numpy as np

print("Check if vector contains infinity value/values:")
X_vector = np.array([-np.inf, 5,3,4,np.inf, 21])
Y_vector = np.array([0,0,0,2,3,4,1,6])

#Identifying infinity
#Variant I
def does_contain_inf1(array):
    for i in np.isfinite(array):
        if i == False:
            print("There is infinity value in given vector")
            return True
    print("Ther is no infinity values in given vector")
    return False

print("\nVariant I:")
does_contain_inf1(X_vector)
does_contain_inf1(Y_vector)

#Variant II
def does_contain_inf2(array):
    for i in np.isinf(array):
        if i == True:
            print("There is infinity value in given vector")
            return True
    print("Ther is no infinity values in given vector")
    return False

print("\nVariant II:")
does_contain_inf2(X_vector)
does_contain_inf2(Y_vector)

#Variant III
def does_contain_inf3(array):
    for i, j in zip(np.isposinf(array), np.isposinf(array)):
        if i == True or j == True:
            print("There is infinity value in given vector")
            return True
    print("Ther is no infinity values in given vector")
    return False

print("\nVariant III:")
does_contain_inf3(X_vector)
does_contain_inf3(Y_vector)


#Identifying zeros

print("\nCheck if vector contains zero value/values: \n ")
print("Varraint I:")
def does_contain_zero1(array):
    if np.count_nonzero(array)==len(array):
        print("There is no zero value in given vector")
        return False
    print("There is zero value in given vector")
    return True

does_contain_zero1(X_vector)
does_contain_zero1(Y_vector)


print("\nVarraint II:")
def does_contain_zero2(array):
    if len(np.flatnonzero(array))==len(array):
        print("There is no zero value in given vector")
        return False
    print("There is zero value in given vector")
    return True

does_contain_zero2(X_vector)
does_contain_zero2(Y_vector)

print("\n Variant III:")
def does_contain_zero3(array):
    if np.nonzero(array)[0].size==len(array):
        print("There is no zero value in given vector")
        return False
    print("There is zero value in given vector")
    return True

does_contain_zero3(X_vector)
does_contain_zero3(Y_vector)

#Comparing matrix I

def compare_matrix_or_vectors1(m1,m2):
    if np.equal(m1,m2).all():
        print("Given matrix/vectors are equal")
    elif np.greater(m1,m2).all():
        print("Values of matrix/vector given as parameter one are greater than values of matrix/vector given as parameter 2")
    elif np.greater_equal(m1,m2).all():
        print("Values of matrix/vector given as parameter one are greater or equal than values of matrix/vector given as parameter 2")
    elif np.less(m1,m2).all():
        print("Values of matrix/vector given as parameter 1 are smaller than values of matrix/vector given as parameter 2")
    elif np.less_equal(m1,m2).all():
        print("Values of matrix/vector given as parameter 1 are smaller or equal than values of matrix/vector given as parameter 2")
    else :
        print("There is no relation between values of given matrix/vector")

#Comparing matrix II


def compare_matrix_or_vectors2(m1, m2):
    if m1.ndim == m2.ndim and m1.size == m2.size:
        return m1 == m2
    elif m1.size > m2.size:
        m2 = np.resize(m2, (1, m1.size))
        m1 = np.resize(m1, (1, m1.size))
        return m1 == m2
    else:
        m1 = np.resize(m2, (1, m2.size))
        m2 = np.resize(m2, (1, m2.size))
        return m1 == m2


m1 = np.array([1, 2, 3, 4, 5])
m2 = np.array([1, 2, 5])
m3 = np.array([[1, 2], [3, 4]])
vec1 = np.array([1,2,3,4])
vec2 = np.array([2,3,4,5])
matrix1 = np.array([[1,1,1], [2,2,2], [3,3,3]])
matrix2 = np.array([[1,1,1], [2,2,2], [3,3,3]])

print("\nVariant I:")
print("\nComparing matrix, method appropriate only for matrix of the same size:")
compare_matrix_or_vectors1(vec2,vec1)
compare_matrix_or_vectors1(vec1,vec2)
compare_matrix_or_vectors1(matrix1,matrix2)

print("\nVariant II: \n")
print("Comparing matrix.:\n")
print(compare_matrix_or_vectors2(m1, m2), '\n')
print(compare_matrix_or_vectors2(m3,m1), '\n')

def are_equal(a,b):
  print("Are matrix equal?", np.array_equal(a,b))
print("\nVariant III: \n")
are_equal(matrix1, matrix2);
are_equal(m1, m2);


Check if vector contains infinity value/values:

Variant I:
There is infinity value in given vector
Ther is no infinity values in given vector

Variant II:
There is infinity value in given vector
Ther is no infinity values in given vector

Variant III:
There is infinity value in given vector
Ther is no infinity values in given vector

Check if vector contains zero value/values: 
 
Varraint I:
There is no zero value in given vector
There is zero value in given vector

Varraint II:
There is no zero value in given vector
There is zero value in given vector

 Variant III:
There is no zero value in given vector
There is zero value in given vector

Variant I:

Comparing matrix, method appropriate only for matrix of the same size:
Values of matrix/vector given as parameter one are greater than values of matrix/vector given as parameter 2
Values of matrix/vector given as parameter 1 are smaller than values of matrix/vector given as parameter 2
Given matrix/vectors are equal

Variant II: 

Comp

### Zadanie 4 
Napisz program, który wylicza ile danych w bajtach zajmuje wektor lub macierz

In [23]:
import numpy as np
from sys import getsizeof

def calculate_bytes_size(Array):
    print("Size of stored data:", Array.nbytes)
    print("Size of stored object:",getsizeof(Array), "\n")

matrix = np.array([[1,2,3,4],[1,2,3,3],[4,5,6,1],[4,4,2,2]])
vector = np.array([1,2,3,4,5,6,7,8,9])

print("Example for matrix: \n")
calculate_bytes_size(matrix)
print("\nExample for vector: \n")
calculate_bytes_size(vector)


Example for matrix: 

Size of stored data: 128
Size of stored object: 240 


Example for vector: 

Size of stored data: 72
Size of stored object: 168 



### Zadanie 5
Napisz kilka programów, które demonstrują jak można w numpy tworzyć wektory i macierze wypełnione różnymi danymi lub mającymi pewną szczególną postać, np. , danymi losowymi, danymi z podanego zakresy, macierze identyczności, ... 

In [30]:
import numpy as np

def create_random_vector(size):
    vector = np.array(np.random.random(size))
    print(vector)
    return vector

print("Vector of given size filled with random values:")
create_random_vector(5)
print('\n\n')

def create_random_vector2(size, min_value, max_value):
    vector = np.array(np.random.uniform(min_value,max_value,size))
    print(vector)
    return vector

print("Vector of given size filled with random values from given interval:")
create_random_vector2(10,2,6)
print('\n\n')

def create_random_matrix(nRows, nCols):
    matrix=np.array(np.random.random((nRows,nCols)))
    print(matrix)
    return matrix

print("Matrix of given size filled with random values:")
create_random_matrix(3,4)
print('\n\n')

def create_random_matrix2(nRows,nCols, min_value, max_value):
    matrix = np.array(np.random.uniform(min_value,max_value,(nRows,nCols)))
    print(matrix)
    return matrix

print("Matrix of given size filled with random values from given interval:")
create_random_matrix2(3,4,2,6)
print('\n\n')

def create_identity_matrix(size):
    matrix = np.array(np.identity(size, dtype = float))
    print(matrix)

print("Identity matrix of given size:")
create_identity_matrix(8)
print('\n\n')

Vector of given size filled with random values:
[0.09416378 0.43021616 0.35480746 0.47966212 0.19197422]



Vector of given size filled with random values from given interval:
[3.30966882 4.43497489 2.32410621 4.76557283 3.05625302 4.02330115
 5.94487316 3.72241273 4.40061532 4.98394981]



Matrix of given size filled with random values:
[[0.69044874 0.36643902 0.81388252 0.99736201]
 [0.02499179 0.60251053 0.02453397 0.10166456]
 [0.98131936 0.29670194 0.12208032 0.55639921]]



Matrix of given size filled with random values from given interval:
[[2.20230088 3.58226108 2.51729179 4.02410833]
 [4.32644767 4.31664086 3.47849861 4.20867916]
 [2.13765474 2.51684593 2.69155537 2.22882792]]



Identity matrix of given size:
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]





### Zadania 6
Napisz programy wykonujący podstawowe operacje algebry: dodawanie wektórów, mnożenie wektorów, mnożenia macierzy. Najpierw napisz je w wersji szkolnej, nie zastanawiając się nad jakąkolwiek optymalizacją. Następnie spróbuj zmienić organizację obliczeń tak by uzyskać poprawę wydajności. Na koniec porównaj swoje metody do dedykowanych funkcji z bibliotek NumPy i SciPy. 


In [21]:
#Vectors addition

#Simple approach
def add (a,b):
  if len(a) != len(b):
    return
  c = np.zeros(len(a))
  for i in range(len(a)):
    c[i]=a[i]+b[i]
  return c

#Better approach
def add_vectors(v, w):
    return [vi + wi for vi, wi in zip(v, w)]

def sum_of_all_vectors(vecs):
    return functools.reduce(add_vectors, vecs)

#Vectors multiplying

#Simple approach
def multiply (a,b):
  if len(a) != len(b):
    return
  c = np.zeros(len(a))
  for i in range(len(a)):
    c[i]=a[i]*b[i]
  return c

#Better approach
def vector_product(v, w):
    return [vi * wi for vi, wi in zip(v, w)]

def product_of_all_vectors(vecs):
    return functools.reduce(vector_product, vecs)

#multiplying matrix

#Simple approach
def matrix_multiply1(X,Y):
    result2=np.zeros((3,4))
    for i in range(len(X)):
       # iterate through columns of Y
       for j in range(len(Y[0])):
           # iterate through rows of Y
           for k in range(len(Y)):
               result2[i][j] += X[i][k] * Y[k][j]
    for r in result2:
       print(r)

#Better approach
def matrix_multiply2(X,Y):
    result = [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*Y)] for X_row in X]
    for r in result:
       print(r)
#Arrays used in examples
arr1 = np.array([1,2,3])
arr2 = np.array([3,4,5])
arr3 = np.array([5,6,7])
arr4 = np.array([1,2,0])
X = np.array([[12,7,3],
    [4 ,5,6],
    [7 ,8,9]])
Y = np.array([[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]])

#ADDING
print("ADDING VECTORS \n\nMy method:")
print("Result of adding two vectors (simple aproach):")
print(add(arr1, arr2))
start = time.time()
add_vectors(arr1, arr2)
end = time.time()
print("Execution time: ", f'{(end-start):.10f}','\n')
print("Result of adding two vectors (better aproach):")
print(add_vectors(arr1, arr2))
start = time.time()
add_vectors(arr1, arr2)
end = time.time()
print("Execution time: ", f'{(end-start):.10f}','\n')

print("\nDifferent predefined methods:\n")
print("Results of adding two vectors using predefined functions np.add or np.sum:")
print("np.sum:", np.sum([arr1, arr2], axis=0)) 
start = time.time()
np.sum([arr1, arr2], axis=0)
end = time.time()
print("Execution time: ", f'{(end-start):.10f}')
print("np.add:", np.add(arr1,arr2))
start = time.time()
np.add(arr1,arr2)
end = time.time()
print("Execution time: ", f'{(end-start):.10f}')
print("'+'': ", arr1+arr2) 
start = time.time()
arr1+arr2
end = time.time()
print("Execution time: ", f'{(end-start):.10f}')

print("\n\nADDING SEVERAL VECTORS \n\nMy method:")
print("Result of adding several (four) vectors:")
arrs = [arr1,arr2,arr3,arr4]
print(sum_of_all_vectors(arrs))
start = time.time()
sum_of_all_vectors(arrs)
end = time.time()
print("Execution time: ", f'{(end-start):.10f}', '\n')

print("Different predefined methods:")
print("Result of adding several (four) vectors using predefined function np.sum with appropriate parameter axis:")
print("np.sum:",np.sum(arrs, axis=0))
start = time.time()
np.sum(arrs, axis=0)
end = time.time()
print("Execution time: ", f'{(end-start):.10f}')

print("\nResult of adding several vectors using '+' for numpy arrays")
print(arr1+arr2+arr3+arr4)
start = time.time()
arr1+arr2+arr3+arr4
end = time.time()
print("Execution time: ", f'{(end-start):.10f}')

#Vectors multiplification
print("\n\nMULTIPLYING VECTORS \n\n My method:")
print("Result of multiplying two vectors (simple approach):")
print(vector_product(arr1,arr2))
start = time.time()
multiply(arr1,arr2)
end = time.time()
print("Execution time: ", f'{(end-start):.10f}')
print("Result of multiplying two vectors (better aproach):")
print(vector_product(arr1,arr2))
start = time.time()
vector_product(arr1,arr2)
end = time.time()
print("Execution time: ", f'{(end-start):.10f}')

print("\nPredefined method:")

print("Result of mulyiplying two vectors using predefined function np.multiply:")
print(np.multiply(arr1,arr2))
start = time.time()
np.multiply(arr1,arr2)
end = time.time()
print("Execution time: ", f'{(end-start):.10f}')

print("\n\nMULTIPLYING SEVRAL VECTORS \n\n My method:")
print("Result of multiplying several (four) vectors:")
print(product_of_all_vectors(arrs))
start = time.time()
product_of_all_vectors(arrs)
end = time.time()
print("Execution time: ", f'{(end-start):.10f}')

print("\nPredefined method:")
print("Result of multiplying several vectors using '*' for numpy arrays:")
print(arr1*arr2*arr3*arr4)
start = time.time()
arr1*arr2*arr3*arr4
end = time.time()
print("Execution time: ", f'{(end-start):.10f}')

print(" \nMATRIX MULTIPLYING (simple approach) \n")
print("My method 1:")
start = time.time()
matrix_multiply1(X,Y)
end = time.time()
print("Execution time: ", f'{(end-start):.10f}')

print("\nMy method 2 (better approach)")
start = time.time()
matrix_multiply2(X,Y)
end = time.time()
print("Execution time: ", f'{(end-start):.10f}')

print("\nResult of multiplying matrix using predefined function: array1.dot(array2):")
print(X.dot(Y))
start = time.time()
X.dot(Y)
end = time.time()
print("Execution time: ", f'{(end-start):.10f}')

print("\nResult of multiplying matrix using predefined function: numpy.matmul(array1, array2):")

print(np.matmul(X,Y));
start = time.time()
np.matmul(X,Y)
end = time.time()
print("Execution time: ", f'{(end-start):.10f}')

ADDING VECTORS 

My method:
Result of adding two vectors (simple aproach):
[4. 6. 8.]
Execution time:  0.0000467300 

Result of adding two vectors (better aproach):
[4, 6, 8]
Execution time:  0.0000579357 


Different predefined methods:

Results of adding two vectors using predefined functions np.add or np.sum:
np.sum: [4 6 8]
Execution time:  0.0000870228
np.add: [4 6 8]
Execution time:  0.0000422001
'+'':  [4 6 8]
Execution time:  0.0000376701


ADDING SEVERAL VECTORS 

My method:
Result of adding several (four) vectors:
[10, 14, 15]
Execution time:  0.0000507832 

Different predefined methods:
Result of adding several (four) vectors using predefined function np.sum with appropriate parameter axis:
np.sum: [10 14 15]
Execution time:  0.0000832081

Result of adding several vectors using '+' for numpy arrays
[10 14 15]
Execution time:  0.0000441074


MULTIPLYING VECTORS 

 My method:
Result of multiplying two vectors (simple approach):
[3, 8, 15]
Execution time:  0.0000448227
Result o